    /************************************************************************
 * MechSys - Open Library for Mechanical Systems                        *
 * Copyright (C) 2009 Sergio Galindo                                    *
 *                                                                      *
 * This program is free software: you can redistribute it and/or modify *
 * it under the terms of the GNU General Public License as published by *
 * the Free Software Foundation, either version 3 of the License, or    *
 * any later version.                                                   *
 *                                                                      *
 * This program is distributed in the hope that it will be useful,      *
 * but WITHOUT ANY WARRANTY; without even the implied warranty of       *
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the         *
 * GNU General Public License for more details.                         *
 *                                                                      *
 * You should have received a copy of the GNU General Public License    *
 * along with this program. If not, see <ttp://www.gnu.org/licenses/>  *
 ************************************************************************/

/////////////////////// 

// MechSys
#include <mechsys/dem/domain.h>
#include <mechsys/util/fatal.h>
#include <mechsys/util/util.h>
#include <mechsys/mesh/unstructured.h>
#include <mechsys/linalg/matvec.h>

using std::cout;
using std::endl;

struct UserData
{
    String   test;                
    double dt;
    double gain;
    double target_p;
    double sxx;
    double syy;
    double szz;
    double eps_zz;
    double CN;
    double rho;
    double radius;
    double limit_inertia;

    std::ofstream oss_ss;         
};

Mat3_t ComputeStress(DEM::Domain& dom)
{
    double V = (dom.Xmax - dom.Xmin) *
               (dom.Ymax - dom.Ymin) *
               (dom.Zmax - dom.Zmin);

     Mat3_t stress; 
    for (int i = 0; i < 3; ++i)
        for (int j = 0; j < 3; ++j)
            stress(i, j) = 0.0;

    for (auto& it : dom.PairtoCInt) {
        DEM::CInteracton* ci = it.second;
        if (norm(ci->Fnet) > 1e-12 || norm(ci->Ftnet) > 1e-12) {
            Vec3_t F = ci->Fnet + ci->Ftnet;
            Vec3_t branch;
            DEM::BranchVec(ci->P2->x, ci->P1->x, branch, dom.Per);
            // Accumulate outer product
            for (int i = 0; i < 3; ++i)
                for (int j = 0; j < 3; ++j)
                    stress(i, j) += F(i) * branch(j);
        }
    }

    for (int i = 0; i < 3; ++i)
        for (int j = 0; j < 3; ++j)
            stress(i, j) /= V;

    return stress;
}


void SetupNor(DEM::Domain& dom, void* UD)   // reference
{
    UserData& dat = *static_cast<UserData*>(UD);

    Mat3_t stress = ComputeStress(dom);   // pass reference


    dat.sxx = stress(0,0);
    dat.syy = stress(1,1);
    dat.szz = stress(2,2);

    double dsxx = -dat.target_p - dat.sxx;
    double dsyy = -dat.target_p - dat.syy;
    double dszz = -dat.target_p - dat.szz;

    double epsdot_xx = -dsxx * dat.gain;
    double epsdot_yy = -dsyy * dat.gain;
    double epsdot_zz;
    if (dat.limit_inertia == 0.0) {
        epsdot_zz = -dszz * dat.gain;
    } else {
        double current_p = -(dat.sxx + dat.syy + dat.szz) / 3.0;
        epsdot_zz = dat.limit_inertia / (dat.radius * 2.0 * sqrt(dat.rho / current_p));
    }

    // update box dimensions
    dom.Xmax *= (1.0 - epsdot_xx * dat.dt);
    dom.Ymax *= (1.0 - epsdot_yy * dat.dt);
    dom.Zmax *= (1.0 - epsdot_zz * dat.dt);
    dom.Per = Vec3_t(dom.Xmax - dom.Xmin,
                     dom.Ymax - dom.Ymin,
                     dom.Zmax - dom.Zmin);



    dat.eps_zz += epsdot_zz * dat.dt;

// cant use PairtoCint directly because that also includes 0 force contacts generated by the verlet list approach
    size_t n_contacts = 0;
    size_t n_particles = dom.Particles.Size();
    for (auto& it : dom.PairtoCInt) {
        DEM::CInteracton* ci = it.second;
        if (norm(ci->Fnet) > 1e-12 || norm(ci->Ftnet) > 1e-12)
            n_contacts++;
    }
    dat.CN = (n_particles > 0) ? 2.0 * n_contacts / n_particles : 0.0; 


}

void ReportNor(DEM::Domain& dom, void* UD)
{
    UserData& dat = *static_cast<UserData*>(UD);



	if (!dom.Finished){
	
	//printf("Lx %g, Ly %g, Lz %g, sxx: %g, syy: %g, sxx: %g, eps_zz: %g, GN: %g\n",dom.Xmax,dom.Ymax,dom.Zmax,dat.sxx,dat.syy,dat.szz,dat.eps_zz,dat.CN);


	   dat.oss_ss << dom.Time << ","
           << dat.sxx << ","
           << dat.syy << ","
           << dat.szz << ","
           << dat.eps_zz << ","
           << dat.CN << std::endl;

    }
    else
    {
        dat.oss_ss.close();
    }
}
int main(int argc, char **argv) try
{


    if (argc<2) throw new Fatal("This program must be called with one argument: the name of the data input file without the '.inp' suffix.\nExample:\t %s filekey\n",argv[0]);

    size_t Nproc = 1; 
    double dthoot= 4.0;     
    if (argc>=3) Nproc =atoi(argv[2]);
    if (argc>=4) dthoot=atof(argv[3]);
    String filekey  (argv[1]);
    String filename (filekey+".inp");
    if (!Util::FileExists(filename)) throw new Fatal("File <%s> not found",filename.CStr());
    ifstream infile(filename.CStr());
    
    double verlet;      // Verlet distance for optimization
    String contactlaw;  // Particle type 
    size_t  RenderVideo;// Decide is video should be render
    String particleList;    // Name of the soil to import
    double Kn;          // Normal stiffness
    double Kt;          // Tangential stiffness
    double Gn;          // Normal dissipative coefficient
    double Gt;          // Tangential dissipative coefficient
    double Mu0;         // Microscopic friction coefficient at the initial stage
    double dt;          // Time step
    double dtOut;       // Time step for output
    double Lx;          // Lx
    double Ly;          // Ly
    double Lz;          // Lz
    double target_p;    // target confining pressure
    double gain;        // for the servo control
    double limit_inertia; // maximum inertia during shearing
    double rho;         // rho
    double Tf;          // Final time for the test
    int num_cells;     // how big the crystal should be
    double radius;    // particle radii
    {
        infile >> verlet;       infile.ignore(200,'\n');
        infile >> contactlaw;   infile.ignore(200,'\n');
        infile >> RenderVideo;  infile.ignore(200,'\n');
        infile >> Kn;           infile.ignore(200,'\n');
        infile >> Kt;           infile.ignore(200,'\n');
        infile >> Gn;           infile.ignore(200,'\n');
        infile >> Gt;           infile.ignore(200,'\n');
        infile >> Mu0;          infile.ignore(200,'\n');
        infile >> rho;          infile.ignore(200,'\n');
        infile >> radius;       infile.ignore(200,'\n'); 
        infile >> num_cells;    infile.ignore(200,'\n'); 
        infile >> dt;           infile.ignore(200,'\n');
        infile >> dtOut;        infile.ignore(200,'\n');
        infile >> target_p;     infile.ignore(200,'\n');
        infile >> gain;     infile.ignore(200,'\n');
        infile >> limit_inertia;infile.ignore(200,'\n');
        infile >> Tf;           infile.ignore(200,'\n');
    }


    size_t cl = 0;
    UserData dat;
    size_t contactLawCode = (contactlaw == "hertz") ? 1 : 0;
    DEM::Domain dom(&dat, contactLawCode);
    dom.Alpha=verlet;
    dom.Dilate = true;

    double a = 2.0 * std::sqrt(2.0) * radius;

    std::vector<Vec3_t> basis = {
        {0.0,           0.0,           0.0},
        {0.5 * a,       0.5 * a,       0.0},
        {0.5 * a,       0.0,           0.5 * a},
        {0.0,           0.5 * a,       0.5 * a}
    };

     std::vector<Vec3_t> positions;

    for (int ix = 0; ix < num_cells; ++ix) {
        for (int iy = 0; iy < num_cells; ++iy) {
            for (int iz = 0; iz < num_cells; ++iz) {
                double cell_origin_x = ix * a;
                double cell_origin_y = iy * a;
                double cell_origin_z = iz * a;

                for (const auto& b : basis) {
                    double x = cell_origin_x + b[0];
                    double y = cell_origin_y + b[1];
                    double z = cell_origin_z + b[2];
                    positions.push_back({x, y, z});
                }
            }
        }
    }

    Lx = a * num_cells;
    Ly = a * num_cells;
    Lz = a * num_cells;

    
    Vec3_t Xmin(0.0,0.0,0.0);
    Vec3_t Xmax(Lx,Ly,Lz);

    printf("Num cells: %i, domsize: %g\n",num_cells,Lx);
    

    dom.Xmax =  Lx;
    dom.Xmin = 0.0;
    dom.Ymax =  Ly;
    dom.Ymin = 0.0;
    dom.Zmax =  Lz;
    dom.Zmin = 0.0;
    dom.Per = Vec3_t(Lx, Ly, Lz);
    
    
    for (const auto& p : positions) 
        dom.AddSphere(-1, p, radius, rho);
    

    for (size_t i=0;i<dom.Particles.Size();i++)
    {
        dom.Particles[i]->Props.Kn    = Kn;
        dom.Particles[i]->Props.Kt    = Kt;
        dom.Particles[i]->Props.Gn    = Gn;
        dom.Particles[i]->Props.Gt    = Gt;
        dom.Particles[i]->Props.Mu    = Mu0;  

        // fix rotational dofs
        dom.Particles[i]->wxf     = true;
        dom.Particles[i]->wyf     = true;
        dom.Particles[i]->wzf     = true;

		// tell the system to consider the particle free for the periodic BCs, even if it has fixed DOFs
		dom.Particles[i]->FixFree = true;

    }
    
    dom.BoundingBox(Xmin,Xmax);
    
    dat.dt = dt;
    dat.radius = radius;
    dat.rho = rho;
    dat.target_p = target_p;
    dat.limit_inertia = 0.0; // zero during compression
    dat.gain = gain;
    
    // compress to target pressure
    dom.Solve (/*tf*/dt*1000, /*dt*/dt, /*dtOut*/dt*1000, &SetupNor, NULL, NULL,RenderVideo,Nproc);


    dat.limit_inertia = limit_inertia;
    dat.eps_zz = 0.0; // reset axial displ
    
    // print to csv
    String fs;
    fs.Printf("%s.csv", filekey.CStr());
    
    
    dat.oss_ss.open(fs.CStr());
    dat.oss_ss << Util::_10_6 << "Time,sxx,syy,szz,eps_ax,CN"<< std::endl;    
    // shear
    dom.Solve (/*tf*/Tf, /*dt*/dt, /*dtOut*/dtOut, &SetupNor, &ReportNor, NULL,RenderVideo,Nproc);


    return 0;
}
MECHSYS_CATCH
